In [11]:
import pandas as pd

In [13]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow'
url = f'{prefix}/yellow_tripdata_2021-01.csv.gz'
url

'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz'

In [23]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates
)

In [22]:
df = pd.read_csv(url)

C:\Users\musta\AppData\Local\Temp\ipykernel_22152\4176769558.py:1: DtypeWarning: Columns (0: store_and_fwd_flag) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

In [24]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [25]:
df['VendorID']

0             1
1             1
2             1
3             1
4             2
           ...
1369760    <NA>
1369761    <NA>
1369762    <NA>
1369763    <NA>
1369764    <NA>
Name: VendorID, Length: 1369765, dtype: Int64

In [19]:
len(df)

1369765

In [34]:
!uv add sqlalchemy "psycopg[binary,pool]"

Resolved 118 packages in 574ms
Prepared 1 package in 286ms
Installed 1 package in 37ms
 + psycopg-pool==3.3.1

In [37]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg://root:root@localhost:5432/ny_taxi')

In [39]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [38]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [57]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000,
)

In [43]:
df = next(df_iter)

In [45]:
for df in df_iter:
    print(len(df))

100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
69765

In [59]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(
        name='yellow_taxi_data',
        con=engine,
        if_exists='append'
    )

0it [00:00, ?it/s]

In [47]:
!uv add tqdm

Resolved 119 packages in 1.35s
Prepared 1 package in 335ms
Installed 1 package in 131ms
 + tqdm==4.67.3

In [49]:
from tqdm.auto import tqdm

In [51]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='yellow_texi_data', con=engine, if_exists='append')

0it [00:00, ?it/s]

In [52]:
engine

Engine(postgresql+psycopg://root:***@localhost:5432/ny_taxi)

In [53]:
engine.connect()

In [55]:
for df_chunk in df_iter:
    print("Chunk received")
    break

In [56]:
small_df = df.head(1000)

small_df.to_sql(
    name='yellow_taxi_data',
    con=engine,
    if_exists='append'
)

-1

In [44]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1,2021-01-04 14:04:31,2021-01-04 14:08:52,3,0.70,1,N,234,224,2,5.0,2.5,0.5,0.00,0.0,0.3,8.30,2.5
99996,1,2021-01-04 14:18:46,2021-01-04 14:35:45,2,3.30,1,N,234,236,1,14.5,2.5,0.5,3.55,0.0,0.3,21.35,2.5
99997,1,2021-01-04 14:42:41,2021-01-04 14:59:22,2,4.70,1,N,236,79,1,17.0,2.5,0.5,4.05,0.0,0.3,24.35,2.5
99998,2,2021-01-04 14:39:02,2021-01-04 15:09:37,2,17.95,2,N,132,148,1,52.0,0.0,0.5,5.00,0.0,0.3,60.30,2.5
99999,2,2021-01-04 14:49:36,2021-01-04 14:54:44,5,0.37,1,N,236,236,2,5.0,0.0,0.5,0.00,0.0,0.3,8.30,2.5

In [60]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 60FE-8CFB

 Directory of C:\Users\musta\Desktop\DataTalksClub\DE-Workshop\pipeline

26/05/2026  04:08 am    <DIR>          .
25/05/2026  07:49 pm    <DIR>          ..
25/05/2026  08:52 pm    <DIR>          .ipynb_checkpoints
22/05/2026  02:38 pm                 5 .python-version
25/05/2026  11:08 pm    <DIR>          .venv
22/05/2026  05:16 pm               657 Dockerfile
22/05/2026  03:58 pm               489 Dockerfile.viren
22/05/2026  02:38 pm                86 main.py
25/05/2026  07:59 pm    <DIR>          ny_taxi_postgres_data
22/05/2026  02:55 pm             2,111 output_12.parquet
22/05/2026  02:34 pm               251 pipeline.py
26/05/2026  12:08 am               353 pyproject.toml
22/05/2026  02:38 pm                 0 README.md
26/05/2026  12:08 am           257,028 uv.lock
               9 File(s)        260,980 bytes
               5 Dir(s)  83,102,412,800 bytes free